'''
Created on 25/02/2012

@author: Nestor
'''

ACCION = { 
          'Insertar': 'inserto',
          'Abrir': 'abrio',
          'Actualizar': 'actualizo',
          'Eliminar': 'elimino',
          'Bloquear': 'bloqueo',
          'Abrir sesion': 'abrio sesion',
          'Cerrar sesion': 'cerro sesion'
}

MENSAJE_DE_ERROR = 'Vos lo que estais es loco! Esa verga no existe'

TABLAS = [
          'acceso',
          'accion',
          'administrador',
          'buscable',
          'busqueda',
          'calificable_seguible',
          'calificacion',
          'calificacion_resena',
          'categoria',
          'cliente',
          'cobrable',
          'codigo_de_error',
          'consumidor',
          'consumidor_objetivo',
          'contador_de_exhibiciones',
          'croquis',
          'describible',
          'descripcion',
          'dia',
          'dibujable',
          'estadisticas',
          'estadisticas_de_influencia',
          'estadisticas_de_popularidad',
          'estadisticas_de_visitas',
          'estadisticas_temporales',
          'estatus',
          'etiqueta',
          'etiquetable',
          'factura',
          'foto',
          'grado_de_instruccion',
          'grado_de_instruccion_objetivo',
          'grupo_de_edad',
          'grupo_de_edad_objetivo',
          'horario_de_trabajo',
          'idioma',
          'interlocutor',
          'inventario',
          'mensaje',
          'palabra',
          'patrocinante',
          'precio_cantidad',
          'privilegios',
          'producto',
          'publicidad',
          'punto',
          'punto_de_croquis',
          'rastreable',
          'region',
          'region_territorio',
          'registro',
          'relacion_de_palabras',
          'resultado_de_busqueda',
          'seguidor',
          'servicio_vendido',
          'sexo',
          'sexo_objetivo',
          'tamano',
          'territorio',
          'territorio_objetivo',
          'tienda',
          'tiendas_consumidores',
          'tipo_de_codigo',
          'turno',
          'usuario',
          'visibilidad',
]