'''
Created on 25/02/2012

@author: Nestor
'''

# Si estais en Windows descomenta este segemento:
TABLAS = [
          'acceso',
          'accion',
          'administrador',
          'buscable',
          'busqueda',
          'calificable_seguible',
          'calificacion',
          'calificacion_resena',
          'categoria',
          'ciudad',
          'cliente',
          'cobrable',
          'codigo_de_error',
          'consumidor',
          'consumidor_objetivo',
          'contador_de_exhibiciones',
          'continente',
          'croquis',
          'describible',
          'descripcion',
          'dia',
          'dibujable',
          'estadisticas',
          'estadisticas_de_influencia',
          'estadisticas_de_popularidad',
          'estadisticas_de_visitas',
          'estadisticas_temporales',
          'estado',
          'estatus',
          'etiqueta',
          'etiquetable',
          'factura',
          'foto',
          'grado_de_instruccion',
          'grado_de_instruccion_objetivo',
          'grupo_de_edad',
          'grupo_de_edad_objetivo',
          'horario_de_trabajo',
          'huso_horario',
          'idioma',
          'interlocutor',
          'inventario',
          'mensaje',
          'municipio',
          'pais',
          'palabra',
          'parroquia',
          'patrocinante',
          'precio_cantidad',
          'privilegios',
          'producto',
          'publicidad',
          'punto',
          'punto_de_croquis',
          'rastreable',
          'region_geografica',
          'region_geografica_objetivo',
          'registro',
          'relacion_de_palabras',
          'resultado_de_busqueda',
          'seguidor',
          'servicio_vendido',
          'sexo',
          'sexo_objetivo',
          'subcontinente',
          'tamano',
          'tienda',
          'tiendas_consumidores',
          'tipo_de_codigo',
          'turno',
          'usuario',
          'visibilidad',
]

INVENTARIO_RECIENTE = [
                       'tienda_id',
                       'producto_id',
                       'codigo',
                       'descripcion',
                       'precio',
                       'cantidad',
]

PRODUCTO = [ 
            'tipo_de_codigo',
            'codigo',
            'estatus',
            'debut_en_el_mercado',
            'largo',
            'ancho',
            'alto',
            'peso',
            'pais_de_origen',
]

PRODUCTO_REDUCIDO = [
                     'producto_id',
                     'codigo',
                     'fabricante',
                     'categoria',
                     'modelo',
                     'nombre',                     
]

CLIENTE = [
           'rastreable_p',
           'describible_p',
           'usuario_p',
           'rif',
           'categoria',
           'estatus',
           'nombre_legal',
           'nombre_comun',
           'telefono',
           'edificio_cc',
           'piso',
           'apartamento',
           'local_no',
           'casa',
           'calle',
           'sector_urb_barrio',
           'pagina_web',
           'facebook',
           'twitter',
]

CLIENTE_REDUCIDO = [
                    'rif',
                    'categoria',
                    'nombre_legal',
                    'nombre_comun',
                    'telefono',
]