'''
Created on 25/02/2012

@author: Nestor
'''

TABLAS_A_OBJETOS = [
                    {'tabla': 'acceso',                     'objeto': 'Acceso'},
                    {'tabla': 'accion',                     'objeto': 'Accion'},
                    {'tabla': 'administrador',              'objeto': 'Administrador'},
                    {'tabla': 'buscable',                   'objeto': 'Buscable'},
                    {'tabla': 'busqueda',                   'objeto': 'Busqueda'},
                    {'tabla': 'calificableseguible',        'objeto': 'CalificableSeguible'},
                    {'tabla': 'calificacion',               'objeto': 'Calificacion'},
                    {'tabla': 'calificacionresena',         'objeto': 'CalificacionResena'},
                    {'tabla': 'categoria',                  'objeto': 'Categoria'},
                    {'tabla': 'ciudad',                     'objeto': 'Ciudad'},
                    {'tabla': 'cliente',                    'objeto': 'Cliente'},
                    {'tabla': 'cobrable',                   'objeto': 'Cobrable'},
                    {'tabla': 'codigodeerror',              'objeto': 'CodigoDeError'},
                    {'tabla': 'consumidor',                 'objeto': 'Consumidor'},
                    {'tabla': 'consumidorobjetivo',         'objeto': 'ConsumidorObjetivo'},
                    {'tabla': 'contadordeexhibiciones',     'objeto': 'ContadorDeExhibiciones'},
                    {'tabla': 'continente',                 'objeto': 'Continente'},
                    {'tabla': 'croquis',                    'objeto': 'Croquis'},
                    {'tabla': 'describible',                'objeto': 'Describible'},
                    {'tabla': 'descripcion',                'objeto': 'Descripcion'},
                    {'tabla': 'dia',                        'objeto': 'Dia'},
                    {'tabla': 'dibujable',                  'objeto': 'Dibujable'},
                    {'tabla': 'estadisticas',               'objeto': 'Estadisticas'},
                    {'tabla': 'estadisticasdeinfluencia',   'objeto': 'EstadisticasDeInfluencia'},
                    {'tabla': 'estadisticasdepopularidad',  'objeto': 'EstadisticasDePopularidad'},
                    {'tabla': 'estadisticasdevisitas',      'objeto': 'EstadisticasDeVisitas'},
                    {'tabla': 'estadisticastemporales',     'objeto': 'EstadisticasTemporales'},
                    {'tabla': 'estado',                     'objeto': 'Estado'},
                    {'tabla': 'estatus',                    'objeto': 'Estatus'},
                    {'tabla': 'etiqueta',                   'objeto': 'Etiqueta'},
                    {'tabla': 'etiquetable',                'objeto': 'Etiquetable'},
                    {'tabla': 'factura',                    'objeto': 'Factura'},
                    {'tabla': 'foto',                       'objeto': 'Foto'},
                    {'tabla': 'gradodeinstruccion',         'objeto': 'GradoDeInstruccion'},
                    {'tabla': 'gradodeinstruccionobjetivo', 'objeto': 'GradoDeInstruccionObjetivo'},
                    {'tabla': 'grupodeedad',                'objeto': 'GrupoDeEdad'},
                    {'tabla': 'grupodeedadobjetivo',        'objeto': 'GrupoDeEdadObjetivo'},
                    {'tabla': 'horariodetrabajo',           'objeto': 'HorarioDeTrabajo'},
                    {'tabla': 'husohorario',                'objeto': 'HusoHorario'},
                    {'tabla': 'idioma',                     'objeto': 'Idioma'},
                    {'tabla': 'interlocutor',               'objeto': 'Interlocutor'},
                    {'tabla': 'inventario',                 'objeto': 'Inventario'},
                    #{'tabla': 'inventariotienda',           'objeto': 'InventarioTienda'},
                    #{'tabla': 'inventarioReciente',         'objeto': 'InventarioReciente'},
                    {'tabla': 'mensaje',                    'objeto': 'Mensaje'},
                    {'tabla': 'municipio',                  'objeto': 'Municipio'},
                    {'tabla': 'pais',                       'objeto': 'Pais'},
                    {'tabla': 'palabra',                    'objeto': 'Palabra'},
                    {'tabla': 'parroquia',                  'objeto': 'Parroquia'},
                    {'tabla': 'patrocinante',               'objeto': 'Patrocinante'},
                    {'tabla': 'preciocantidad',             'objeto': 'PrecioCantidad'},
                    {'tabla': 'privilegios',                'objeto': 'Privilegios'},
                    {'tabla': 'producto',                   'objeto': 'Producto'},
                    {'tabla': 'publicidad',                 'objeto': 'Publicidad'},
                    {'tabla': 'punto',                      'objeto': 'Punto'},
                    {'tabla': 'puntodecroquis',             'objeto': 'PuntoDeCroquis'},
                    {'tabla': 'rastreable',                 'objeto': 'Rastreable'},
                    {'tabla': 'regiongeografica',           'objeto': 'RegionGeografica'},
                    {'tabla': 'regiongeograficaobjetivo',   'objeto': 'RegionGeograficaObjetivo'},
                    {'tabla': 'registro',                   'objeto': 'Registro'},
                    {'tabla': 'relaciondepalabras',         'objeto': 'RelacionDePalabras'},
                    {'tabla': 'resultadodebusqueda',        'objeto': 'ResultadoDeBusqueda'},
                    {'tabla': 'seguidor',                   'objeto': 'Seguidor'},
                    {'tabla': 'serviciovendido',            'objeto': 'ServicioVendido'},
                    {'tabla': 'sexo',                       'objeto': 'Sexo'},
                    {'tabla': 'sexoobjetivo',               'objeto': 'SexoObjetivo'},
                    {'tabla': 'subcontinente',              'objeto': 'SubContinente'},
                    {'tabla': 'tamano',                     'objeto': 'Tamano'},
                    {'tabla': 'tienda',                     'objeto': 'Tienda'},
                    {'tabla': 'tiendasconsumidores',        'objeto': 'TiendasConsumidores'},
                    {'tabla': 'tipodecodigo',               'objeto': 'TipoDeCodigo'},
                    {'tabla': 'turno',                      'objeto': 'Turno'},
                    {'tabla': 'usuario',                    'objeto': 'Usuario'},
                    {'tabla': 'visibilidad',                'objeto': 'Visibilidad'},
]

INVENTARIO_RECIENTE = [ 
                   'TiendaID', 
                   'ProductoID', 
                   'Codigo', 
                   'Descripcion', 
                   'Precio', 
                   'Cantidad' 
]

PRODUCTO = [ 
            'Rastreable_P', 
            'Describible_P', 
            'Buscable_P',
            'CalificableSeguible_P',
            'ProductoID',
            'TipoDeCodigo',
            'Codigo',
            'Estatus',
            'Fabricante',
            'Modelo',
            'Nombre',
            'Categoria',
            'DebutEnElMercado',
            'Largo',
            'Ancho',
            'Alto',
            'Peso',
            'PaisDeOrigen'
]

TIENDA = [
          'Buscable_P',
          'Cliente_P',
          'CalificableSeguible_P',
          'Interlocutor_P',
          'Dibujable_P',
          'TiendaID',
          'Abierto'
]

CLIENTE = [
           'Rastreable_P',
           'Describible_P',
           'Usuario_P',
           'RIF',
           'Categoria',
           'Estatus',
           'NombreLegal',
           'NombreComun',
           'Telefono',
           'Edificio_CC',
           'Piso',
           'Apartamento',
           'LocalNo',
           'Casa',
           'Calle',
           'Sector_Urb_Barrio',
           'PaginaWeb',
           'Facebook',
           'Twitter'
]
